from __future__ import annotations

import yaml


def test_config_ui_mvp_first_screen_structure(monkeypatch, tmp_path) -> None:
    from config_ui import app as config_app

    config_path = tmp_path / "config.yml"
    config_path.write_text(
        "investor_currency: USD\n"
        "tickers:\n  - VOO\n"
        "current_weights:\n  VOO: 1.0\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(config_app, "CONFIG_PATH", config_path)

    response = config_app.app.test_client().get("/")
    assert response.status_code == 200
    html = response.data.decode("utf-8")
    assert 'class="mvp-panel"' in html
    assert "Core MVP needs three inputs" in html
    assert 'id="advancedSettings"' in html
    assert 'name="investor_currency"' in html
    assert 'name="current_weight[]"' in html
    assert 'name="analysis_mode"' in html
    assert "Liquidity and cash policy" in html
    assert 'name="client_profile"' in html


def test_config_ui_generate_mvp_compact_yaml_by_default(monkeypatch, tmp_path) -> None:
    from config_ui import app as config_app

    config_path = tmp_path / "config.yml"
    config_path.write_text(
        "output_dir: results_csv\n"
        "output_dir_final: Main portfolio\n",
        encoding="utf-8",
    )
    monkeypatch.setattr(config_app, "CONFIG_PATH", config_path)

    response = config_app.app.test_client().post(
        "/generate",
        data={
            "investor_currency": "USD",
            "ticker[]": ["VOO", "BND"],
            "current_weight[]": ["60%", "40%"],
        },
    )
    assert response.status_code == 200
    payload = response.get_json()
    assert payload["success"] is True
    yaml_text = payload["yaml"]
    assert "Core MVP (generated by Config UI)" in yaml_text
    assert "current_weights:" in yaml_text
    assert "client_profile:" not in yaml_text
    config = yaml.safe_load(yaml_text)
    assert config["investor_currency"] == "USD"
    assert config["current_weights"] == {"VOO": 0.6, "BND": 0.4}
    assert config["output_dir"] == "results_csv"


def test_config_ui_generate_full_yaml_for_optimize_mode(monkeypatch, tmp_path) -> None:
    from config_ui import app as config_app

    config_path = tmp_path / "config.yml"
    config_path.write_text("{}", encoding="utf-8")
    monkeypatch.setattr(config_app, "CONFIG_PATH", config_path)

    response = config_app.app.test_client().post(
        "/generate",
        data={
            "analysis_mode": "optimize_from_universe",
            "investor_currency": "USD",
            "initial_investable_amount": "1000",
            "ticker[]": ["VOO", "BND"],
            "current_weight[]": ["70%", "30%"],
        },
    )
    assert response.status_code == 200
    yaml_text = response.get_json()["yaml"]
    assert "SECTION 1: CORE SETTINGS" in yaml_text
    config = yaml.safe_load(yaml_text)
    assert config["analysis_mode"] == "optimize_from_universe"
    assert config["current_weights"] == {}


def test_config_ui_run_portfolio_review_endpoint(monkeypatch, tmp_path) -> None:
    from config_ui import app as config_app

    config_path = tmp_path / "config.yml"
    config_path.write_text("investor_currency: USD\n", encoding="utf-8")
    monkeypatch.setattr(config_app, "CONFIG_PATH", config_path)

    calls: list[list[str]] = []

    def fake_run(cmd, **kwargs):
        calls.append(cmd)
        class Result:
            returncode = 0
            stdout = "dry-run ok"
            stderr = ""

        return Result()

    monkeypatch.setattr(config_app.subprocess, "run", fake_run)

    response = config_app.app.test_client().post(
        "/run-portfolio-review",
        json={"dry_run": True},
    )
    assert response.status_code == 200
    payload = response.get_json()
    assert payload["success"] is True
    assert "--dry-run" in calls[0]
