from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
ETF_PATH = ROOT / "config" / "etf_universe.yml"
STOCK_PATH = ROOT / "config" / "stock_universe.yml"
OUT_PATH = ROOT / "frontend" / "data" / "instrumentUniverse.ts"

CASH_POSITIONS = [
    {"ticker": "CASH_USD", "instrument": "USD liquidity position", "kind": "cash", "sleeve": "cash", "currency": "USD", "searchTerms": ["cash", "usd", "liquidity"]},
    {"ticker": "CASH_EUR", "instrument": "EUR liquidity position", "kind": "cash", "sleeve": "cash", "currency": "EUR", "searchTerms": ["cash", "eur", "liquidity"]},
]


def load_yaml(path: Path) -> list[dict[str, Any]]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise TypeError(f"{path} must contain a YAML list")
    return [row for row in data if isinstance(row, dict)]


def normalize_ticker(value: Any) -> str:
    return str(value or "").strip().upper()


def text(value: Any) -> str:
    return str(value or "").strip()


def list_terms(value: Any) -> list[str]:
    if isinstance(value, list):
        return [text(item) for item in value if text(item)]
    value_text = text(value)
    return [value_text] if value_text else []


def sleeve_from_asset_class(value: Any, fallback: str = "other") -> str:
    normalized = text(value).lower().replace("-", "_").replace(" ", "_")
    if normalized in {"equity", "stock", "stocks"}:
        return "equity"
    if normalized in {"fixed_income", "bond", "bonds", "treasury", "cash_like"}:
        return "fixed_income"
    if normalized in {"gold"}:
        return "gold"
    if normalized in {"commodity", "commodities"}:
        return "commodity"
    if normalized in {"multi_asset", "balanced", "allocation"}:
        return "multi_asset"
    return fallback


def compact_terms(*values: Any) -> list[str]:
    seen: set[str] = set()
    result: list[str] = []
    for value in values:
        for term in list_terms(value):
            key = term.lower()
            if key and key not in seen:
                seen.add(key)
                result.append(term)
    return result[:14]


def etf_to_instrument(row: dict[str, Any]) -> dict[str, Any] | None:
    ticker = normalize_ticker(row.get("ticker"))
    name = text(row.get("name"))
    if not ticker or not name:
        return None
    return {
        "ticker": ticker,
        "instrument": name,
        "kind": "fund",
        "sleeve": sleeve_from_asset_class(row.get("asset_class")),
        "currency": text(row.get("currency_exposure")) or None,
        "searchTerms": compact_terms(
            row.get("issuer"),
            row.get("asset_class"),
            row.get("subtype"),
            row.get("sector"),
            row.get("region"),
            row.get("main_risk_factor"),
            row.get("risk_role"),
            row.get("secondary_risk_factors"),
            row.get("thematic_primary"),
            row.get("thematic_tags"),
        ),
    }


def stock_to_instrument(row: dict[str, Any]) -> dict[str, Any] | None:
    ticker = normalize_ticker(row.get("ticker"))
    name = text(row.get("company_name"))
    if not ticker or not name:
        return None
    return {
        "ticker": ticker,
        "instrument": name,
        "kind": "stock",
        "sleeve": "equity",
        "currency": text(row.get("currency_exposure")) or None,
        "searchTerms": compact_terms(
            row.get("asset_class"),
            row.get("sector"),
            row.get("industry"),
            row.get("region"),
            row.get("main_risk_factor"),
            row.get("risk_role"),
            row.get("secondary_risk_factors"),
            row.get("index_membership"),
            row.get("thematic_tags"),
        ),
    }


def without_none(value: dict[str, Any]) -> dict[str, Any]:
    return {key: item for key, item in value.items() if item is not None and item != []}


def main() -> None:
    instruments: list[dict[str, Any]] = []
    instruments.extend(CASH_POSITIONS)
    instruments.extend(filter(None, (etf_to_instrument(row) for row in load_yaml(ETF_PATH))))
    instruments.extend(filter(None, (stock_to_instrument(row) for row in load_yaml(STOCK_PATH))))

    deduped: dict[str, dict[str, Any]] = {}
    for instrument in instruments:
        ticker = instrument["ticker"]
        # Prefer the first canonical source when duplicate tickers exist.
        deduped.setdefault(ticker, without_none(instrument))

    ordered = sorted(deduped.values(), key=lambda item: (item["kind"] != "cash", item["ticker"]))
    body = json.dumps(ordered, ensure_ascii=False, indent=2)
    OUT_PATH.write_text(
        "// Generated by scripts/generate_frontend_instrument_universe.py from config/etf_universe.yml and config/stock_universe.yml.\n"
        "// Do not edit rows manually; update the canonical YAML taxonomies and regenerate.\n\n"
        "export type InstrumentKind = \"fund\" | \"stock\" | \"cash\";\n"
        "export type InstrumentSleeve = \"equity\" | \"fixed_income\" | \"gold\" | \"cash\" | \"commodity\" | \"multi_asset\" | \"other\";\n\n"
        "export type Instrument = {\n"
        "  ticker: string;\n"
        "  instrument: string;\n"
        "  kind: InstrumentKind;\n"
        "  sleeve: InstrumentSleeve;\n"
        "  currency?: string;\n"
        "  searchTerms?: string[];\n"
        "};\n\n"
        f"export const instrumentUniverse: Instrument[] = {body};\n\n"
        "export const instrumentByTicker = new Map(instrumentUniverse.map((item) => [item.ticker, item]));\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(ordered)} instruments to {OUT_PATH}")


if __name__ == "__main__":
    main()
