"""Generate frontend TypeScript API types from the FastAPI OpenAPI schema.

This generator is intentionally dependency-free so the Session 03 contract can
be regenerated from the Python environment without adding a frontend codegen
package. It covers the schema features emitted by the current Pydantic models.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = REPO_ROOT / "frontend" / "lib" / "generated" / "api-types.ts"
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from src.api.app import app  # noqa: E402


def _literal(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def _prop_name(name: str) -> str:
    if name.replace("_", "").isalnum() and (name[0].isalpha() or name[0] == "_"):
        return name
    return _literal(name)


def _ref_name(ref: str) -> str:
    prefix = "#/components/schemas/"
    if not ref.startswith(prefix):
        return "unknown"
    return ref[len(prefix) :]


def _type_alias_name(schema_name: str) -> str:
    parts = [part for part in re.split(r"[^0-9A-Za-z]+", schema_name) if part]
    alias = "".join(part[:1].upper() + part[1:] for part in parts) or "AnonymousSchema"
    if alias[0].isdigit():
        return f"_{alias}"
    return alias


def _schema_to_ts(schema: dict[str, Any] | bool | None) -> str:
    if schema is None or schema is True:
        return "unknown"
    if schema is False:
        return "never"

    if "$ref" in schema:
        return f'Components["schemas"]["{_ref_name(schema["$ref"])}"]'

    if "const" in schema:
        return _literal(schema["const"])

    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"]) or "never"

    for union_key in ("anyOf", "oneOf"):
        if union_key in schema:
            return " | ".join(_schema_to_ts(option) for option in schema[union_key])

    if "allOf" in schema:
        return " & ".join(_schema_to_ts(option) for option in schema["allOf"])

    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(_schema_to_ts({**schema, "type": item}) for item in schema_type)

    if schema_type == "string":
        return "string"
    if schema_type in {"number", "integer"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = _schema_to_ts(schema.get("items", {}))
        return f"Array<{item_type}>"
    if schema_type == "object" or "properties" in schema:
        properties: dict[str, Any] = schema.get("properties") or {}
        required = set(schema.get("required") or [])
        additional = schema.get("additionalProperties", None)
        parts: list[str] = ["{"]
        for prop, prop_schema in sorted(properties.items()):
            optional = "" if prop in required else "..."
            parts.append(f"  {_prop_name(prop)}{optional}: {_schema_to_ts(prop_schema)};")
        if additional and additional is not False:
            parts.append(f"  [key: string]: {_schema_to_ts(additional if isinstance(additional, dict) else {})};")
        parts.append("}")
        return "\n".join(parts)

    return "unknown"


def _operation_response_schema(operation: dict[str, Any]) -> tuple[str, str]:
    responses: dict[str, Any] = operation.get("responses") or {}
    preferred_statuses = ["200", "201", "202", "501", "400", "404", "500"]
    ordered_statuses = preferred_statuses + sorted(status for status in responses if status not in preferred_statuses)
    for status_code in ordered_statuses:
        response = responses.get(status_code) or {}
        schema = response.get("content", {}).get("application/json", {}).get("schema")
        if schema:
            return status_code, _schema_to_ts(schema)
    return "default", "unknown"


def _operation_request_schema(operation: dict[str, Any]) -> str:
    schema = (
        operation.get("requestBody", {})
        .get("content", {})
        .get("application/json", {})
        .get("schema")
    )
    if not schema:
        return "never"
    return _schema_to_ts(schema)


def render_types(openapi_schema: dict[str, Any]) -> str:
    """Render a TypeScript contract file from an OpenAPI schema."""

    schemas: dict[str, Any] = openapi_schema.get("components", {}).get("schemas") or {}
    lines: list[str] = [
        "/* eslint-disable */",
        "/*",
        " * Auto-generated by scripts/generate_fastapi_api_types.py.",
        " * Do not edit by hand; regenerate after FastAPI contract changes.",
        " */",
        "",
        "export interface Components {",
        "  schemas: {",
    ]

    for name in sorted(schemas):
        rendered = _schema_to_ts(schemas[name]).replace("\n", "\n    ")
        lines.append(f'    "{name}": {rendered};')

    lines.extend(
        [
            "  };",
            "}",
            "",
        ]
    )

    for name in sorted(schemas):
        alias = _type_alias_name(name)
        lines.append(f'export type {alias} = Components["schemas"]["{name}"];')

    lines.extend(["", "export interface Operations {"])
    paths: dict[str, Any] = openapi_schema.get("paths") or {}
    for path in sorted(paths):
        path_item: dict[str, Any] = paths[path]
        for method in sorted(path_item):
            operation = path_item[method]
            operation_id = operation.get("operationId") or f"{method}_{path}"
            status_code, response_type = _operation_response_schema(operation)
            request_type = _operation_request_schema(operation)
            lines.extend(
                [
                    f'  "{operation_id}": {{',
                    f'    method: "{method.upper()}";',
                    f"    path: {_literal(path)};",
                    f"    request: {request_type};",
                    f"    response: {response_type};",
                    f'    responseStatus: "{status_code}";',
                    "  };",
                ]
            )
    lines.extend(
        [
            "}",
            "",
            "export type OperationId = keyof Operations;",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(render_types(app.openapi()), encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
